stages:
  - deploy

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

after_script:
  - docker rmi $(docker images -q -f dangling=true)

build-and-run:
  stage: deploy
  script:
    - docker-compose -p checkers stop
    - docker-compose -p checkers rm -f 
    - docker-compose -p checkers up -d --build
  only:
    - stable
  tags:
    - docker
    - s2.clienddev.ru